services:
  - type: web
    name: newsure-backend
    env: python
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn newssure.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: newssure.settings
      - key: PYTHON_VERSION
        value: 3.12.1
