services:
  - type: web
    name: newsure-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn newssure.wsgi"
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.12.0
